apiVersion: apps/v1
kind: Deployment
metadata:
  name: logoutput
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logoutput
  template:
    metadata:
      labels:
        app: logoutput
    spec:
      volumes:
        - name: shared-log
          emptyDir: {}
      containers:
        - name: logoutput
          image: megaeonise/logoutput:v9
          volumeMounts:
            - name: shared-log
              mountPath: /usr/src/app/files
          resources:
            limits:
              memory: 512Mi
            requests:
              memory: 256Mi
              cpu: "0.2"
        - name: logwriter
          image: megaeonise/logwriter:v6
          volumeMounts:
            - name: shared-log
              mountPath: /usr/src/app/files
          resources:
            limits:
              memory: 512Mi
            requests:
              memory: 256Mi
              cpu: "0.2"