apiVersion: apps/v1
kind: Deployment
metadata:
  name: logoutput
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logoutput
  template:
    metadata:
      labels:
        app: logoutput
    spec:
      containers:
        - name: logoutput
          image: megaeonise/logoutput:v1
          resources:
            limits:
              memory: 512Mi
            requests:
              memory: 256Mi
              cpu: "0.2"